name: xpense
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  fpdart: ^0.4.0
  appwrite: ^8.2.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^7.7.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
